#
# Example .travis.yml file.
#
# Copy to your project and rename to .travis.yml.
# Customize per the instructions below.
#
language: php

php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  global:
    # Your site's name -- used in `drush site-install`.
    - SITE_NAME='Maggi Vietnam'

    # Your Pantheon site's idenfying name (i.e. as shown on the dashboard)
    - PSITE='maggi-panopoly-travis-ci'

    # The Pantheon environment to push to after tests succeed.
    # DANGER: This environment will be switched from 'sftp' mode to 'git' mode
    # on every commit to github.  This will ERASE any uncommitted change made in
    # 'sftp' mode.  It is therefore advisable to avoid using 'sftp' mode on
    # the environment you select here. Create a multidev branch specifically for
    # use by Travis.
    - PENV='dev'

    # SECRET/PRIVATE VARIABLES
    #
    # These are created by using the travis command locally to encrypt some values.
    #
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    # PEMAIL environment variable: represents the Pantheon account e-mail with
    # access to this site. Used to authenticate to Pantheon via Terminus. You
    # must cd to your project root and run:
    #
    # travis encrypt PEMAIL='test@example.com'
    #
    - secure: rJSt8fMzzKDNl+KNQ7V0eMbidVCeaUM9X+jw3RFLqPmvHo3CVTRXNK3Z9HqCFa+XBQ5lOnSX1YFTnvgtOOUgigcJyxYxZrUWvlEDuFofHpub4Qira94sXcqkvVLfPlHdEhCG4XAUOjrI7b6BAx93KcscWpRu/LbmiBqCtR/H6OQGJfIXUQmjmNNsQsHGpSI98ehL2NVrupJEgMQLYoZeGCl8ab3W0YBzR/X7YJ5lNG1NHnMedaVFsnBfkQpeyIhAcQI7odYH/PjYbzE75DFD+xuPMz7rJURKb/URMZZsO5nF4Q2/VPHrd4MFoNwAm3uxqfRP3/KiJghV24BrXL9+OhklB7qrMDf2stKHneDJ/dkEUPS5Q881zMwU8MzUGz6zlxr6dh3LzwdFWA06XwTPmq6HiNMVyH8zTE931XhK3dUrz7B/uT+gDZayuDWtjrbZvZeI8sMeOb3RAg8TYzmhckCQ+CAqsTcciYiITCsLdfc4Gk3+RmKARLMjR6LtlUvly0Mjnq7xM8T4CVUH/Cy7ZihJlUSdcEFnrZjDs7qrgD1USfCQuRW4C35hg8C6kqEb7HPvnaTTSdb6qhtliBsYpRHvCfy1CCxYnFwBSCIST+f8Lc6e44a8dYFii6AcepwPlnrYbBHLo2fxkKGT2rPrumoEPtTdvzyYVyA1XiYj9AA=
    #
    # PPASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt PPASS='my_account_password'
    #
    - secure: MAj/MbAqno6aJHPoOikG6lrzr+XcMD3ZtE9CdTfgAOczbXldIKVqmqgmjVeT+UF99tDPbgXSfxpKJn0OFEsE495fPb7SHRZA3QKOJgID5w/rDYFOqfLM4eHCLdIoNtMXGF70LcXNRCsw1B4Y32jxwZopGFTnbhb31KkcQ4O8dhPolmLVPx9U1tu1iLDWi4NdY6kJ3oQEcsdPCWHV4E3+LGnF0A5ui96PYWUoWMTWAUH38dDLZ2f5ADbiZjJSeSNjYcuQ8M8bszEi9Z4K1fL8oAgAKeTJobfhS2ZaXM1eS9NnJYR47RS7bTbF+vUX5OGUoRNN6XwFFjhmrQQBxQMIRStJZcWeVT6nABKRirP2DtKZXQVOSMZzt/RDqp89idnaVCUjhiZiEqPdvYc+YRfJ5JFIaUxlPZ2eX0xaQfO6/+5Oi6wQLWnJY0FPR4UGyFS8BJi1dikZh6R9ygbpBFkW9UN/RwuvkWmjUvtgXlSBaIBFoGhdK31FMn3CReWZHRv2Wx0BbQeyLfZSm5S7Qk3ahib95e9dMxLnW/mBMyM+vRnTZHya2Svq1JZ8Mj1IJGbJAf4DlF9/a0M8JupUpTBrPtzZSfVYGdw1iYrlmelvn6eTPyVqCjn6NsAnhpU4q89tHLozNXoP5PVIKeToseVCuVe2LSQjVcTMU26sO3at5Fk=

before_install:
  # Make sure composer is up-to-date
  - composer self-update
  # Get netstat
  - sudo apt-get update -qq
  - sudo apt-get install net-tools


install:
  - composer install

before_script:
  # Discard any emails Drupal tries to send.
  - bin/disable-php-email

script:
  # Run our behat tests on Travis
  # Install Drupal and launch the PHP built-in webserver
  - bash bin/setup-before-tests
  - bin/behat

after_success:
  # Place a passphrase-free ssh key so that you can clone and push to your
  # Pantheon git repository.
  #
  # Use the travis encrypt-file command to generate your own.
  #
  # See: http://docs.travis-ci.com/user/encrypting-files/
  #
  - openssl aes-256-cbc -K $encrypted_6383b601f5c2_key -iv $encrypted_6383b601f5c2_iv -in travis-ci-key.enc -out travis-ci-key -d
  - cp travis-ci-key ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - bash bin/push-to-pantheon

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - bin/stop-webserver
  - rm $HOME/server.log

notifications:
  email:
    recipients:
      # - ci-notifications@myorg.org
    on_success: always
    on_failure: always

