#
# Example .travis.yml file.
#
# Copy to your project and rename to .travis.yml.
# Customize per the instructions below.
#
language: php

php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  global:
    # Your site's name -- used in `drush site-install`.
    - SITE_NAME='Maggi Vietnam'

    # Your Pantheon site's idenfying name (i.e. as shown on the dashboard)
    - PSITE='maggi-dev'

    # The Pantheon environment to push to after tests succeed.
    # DANGER: This environment will be switched from 'sftp' mode to 'git' mode
    # on every commit to github.  This will ERASE any uncommitted change made in
    # 'sftp' mode.  It is therefore advisable to avoid using 'sftp' mode on
    # the environment you select here. Create a multidev branch specifically for
    # use by Travis.
    - PENV='dev'

    # SECRET/PRIVATE VARIABLES
    #
    # These are created by using the travis command locally to encrypt some values.
    #
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    # PEMAIL environment variable: represents the Pantheon account e-mail with
    # access to this site. Used to authenticate to Pantheon via Terminus. You
    # must cd to your project root and run:
    #
    # travis encrypt PEMAIL=''
    #
    - secure: bmTlWA6fzEdjjfxvg1Futtn4rYeVPSue+Jwlw6WczW8jPACNybQKlWvzyPwm/u5bAMM1JsVxOr626x/cRsChBkbxC+ZP770i9IRZuqOojor2McTUfmUQGRc/LhYQsdVqygvs8/Sccyjzk05I9+uQKo3h2AkEgyvd+Cn2TEHQheQ8elut4DW3wVrEMlGyMv/HTNWXrzYK9o+vEamycYUwXVGATH+zFyDEPpXNfK6a/wEaBaPPq6cMX0USn4sIXONkCnVzg9q3ECkJQwGIpW0t+7LDQ+wSZLj7CLBn1Qkw/jxB4DTl1KkYjCSFbW0HxjVhmk2niOU4D6mRG2nwEtlqhmz8f9gUBFbRNTaOb8UVDEvMIxPKHxj5knAUJOs+QV7s1xmwbemt5YTdAzxYJ3wo1kbSYGC7aLHYRbKGfpGY+wz5VbJKLoE/bY5ZGMs+M5+8iQoJPYIc9KUZDV5L/b6aHiJ2OWWR/3T4Krvl5aAdQDsz04DP/58I+prqsOy4mnrWHwB3eGOxUM+KAjd1LowUFAFN4wV3AVneRCSub9l5v5S2k5Eem8DO8z5/jsDep9FMX1qo3o3oIRD9Di/IEUpz34e6WUwHQi40JxSiElGDyPpzlE+3hT6XANl+mqBKae0+xCKqez0cDxUx6LoEM72R2efhtj94DCRfSRHzBZXkXu4=
    #
    # PPASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt PPASS=''
    #
    - secure: DsXl2MDT0EFJZbmIkajiQuT/jFUEBxdHHqS03NMuCPJ3trxX/eECqeczM7HGEtMzikEpkXTjHW5ZKvmBfbQ/5DagGSlHoGjst/O/9u00uo72G7HR5u++taAPErI1uZUoKYgdec9yxd2sPSqALVjuZor4SvvTNsdvLIq9YTOXzsEQ9R3yjlUUAAm4RxG5DaRCOjkMePYpnVcKXU5aF3Uqi+ywVygMzcu2kzv6r9xpI6wHdw9J91GKllQ81beFOm+/ByNPJcUvpPfRaTCMrISpos+gYt4zdOoxbExE323mO4mLfJwMF/XC3eonTK3U4sB7X0ndUal8INVKNLsze6vAssiZFwircrL96IERG/0+ba6l/qiWo7YIAeQJ8l/frAXBioHCZDr9knf80w2WbVdTCOry3zqjM4bLWNOB5eemBpaBGijVi68hV5U4poYXh1XKIaEZ9tdWMS4RcZVT/00ZG6Mdubat/7lTW827C83XJnp2MG4Rp6LUIsOlixmtIcTLF0auEEmeavhuVT8v2fQtnF727gQm/ca9Op+VfoGwxPuhfyVyESyMyrgZKF6DudmvrDW6RU0NgwaPNhG4b8LGN66RPUzbXzlDOLv3fmW+oq3BHxgjd5dAyz0z9uH3r7xd6vNOhsLtOKW6AZY2xq5jDj1T4HR1IxSHIyvZntuJN3U=

before_install:
  # Make sure composer is up-to-date
  - composer self-update
  # Get netstat
  - sudo apt-get update -qq
  - sudo apt-get install net-tools


install:
  - composer install

before_script:
  # Discard any emails Drupal tries to send.
  - bin/disable-php-email

script:
  # Run our behat tests on Travis
  # Install Drupal and launch the PHP built-in webserver
  - bash bin/setup-before-tests
  - bin/behat

after_success:
  # Place a passphrase-free ssh key so that you can clone and push to your
  # Pantheon git repository.
  #
  # Use the travis encrypt-file command to generate your own.
  #
  # See: http://docs.travis-ci.com/user/encrypting-files/
  #
  - openssl aes-256-cbc -K $encrypted_6d54bee8bd7d_key -iv $encrypted_6d54bee8bd7d_iv -in travis-ci-key.enc -out travis-ci-key -d
  - cp travis-ci-key ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - bash bin/push-to-pantheon

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - bin/stop-webserver
  - rm $HOME/server.log

notifications:
  email:
    recipients:
      # - ci-notifications@myorg.org
    on_success: always
    on_failure: always

